/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.19).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.fattazzo.pizzashop.controller.api;

import com.fattazzo.pizzashop.model.api.Company;
import org.springframework.core.io.Resource;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.bind.annotation.CookieValue;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2020-04-25T15:30:26.294Z[GMT]")
@Api(value = "company", description = "the company API")
public interface CompanyApi {

    @ApiOperation(value = "Get a Company", nickname = "getCompany", notes = "Gets the details of a single instance of a `Company`.", response = Company.class, authorizations = {
        @Authorization(value = "BearerAuth")    }, tags={ "companies", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Successful response - returns a single `Company`.", response = Company.class) })
    @RequestMapping(value = "/company",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<Company> getCompany();


    @ApiOperation(value = "Company logo", nickname = "getLogo", notes = "Get a `Company` logo image", response = Resource.class, authorizations = {
        @Authorization(value = "BearerAuth")    }, tags={ "companies", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Logo image", response = Resource.class) })
    @RequestMapping(value = "/company/logo",
        produces = { "image/png" }, 
        method = RequestMethod.GET)
    ResponseEntity<Resource> getLogo();


    @ApiOperation(value = "Update a Company", nickname = "updateCompany", notes = "Updates an existing `Company`.", response = Company.class, authorizations = {
        @Authorization(value = "BearerAuth")    }, tags={ "companies", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Successful response.", response = Company.class) })
    @RequestMapping(value = "/company",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.PUT)
    ResponseEntity<Company> updateCompany(@ApiParam(value = "Updated `Company` information." ,required=true )  @Valid @RequestBody Company body
);


    @ApiOperation(value = "Update a Company logo", nickname = "updateLogo", notes = "Updates an existing `Company` logo.", authorizations = {
        @Authorization(value = "BearerAuth")    }, tags={ "companies", })
    @ApiResponses(value = { 
        @ApiResponse(code = 204, message = "Successful response.") })
    @RequestMapping(value = "/company/logo",
        consumes = { "multipart/form-data" },
        method = RequestMethod.PUT)
    ResponseEntity<Void> updateLogo(@ApiParam(value = "file detail") @Valid @RequestPart("file") MultipartFile file
);

}
