/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.19).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.fattazzo.pizzashop.controller.api;

import com.fattazzo.pizzashop.model.api.Category;
import com.fattazzo.pizzashop.model.api.CategoryDetails;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.bind.annotation.CookieValue;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
@Api(value = "Pizzacategories", description = "the Pizzacategories API")
public interface PizzacategoriesApi {

    @ApiOperation(value = "Create a pizza Category", nickname = "createPizzaCategory", notes = "Creates a new instance of a pizza `Category`.", response = CategoryDetails.class, authorizations = {
        @Authorization(value = "BearerAuth")    }, tags={ "pizzacategories", })
    @ApiResponses(value = { 
        @ApiResponse(code = 201, message = "Successful response.", response = CategoryDetails.class) })
    @RequestMapping(value = "/pizza/categories",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<CategoryDetails> createPizzaCategory(@ApiParam(value = "A new pizza `Category` to be created." ,required=true )  @Valid @RequestBody CategoryDetails body
);


    @ApiOperation(value = "Delete a pizza Category", nickname = "deletePizzaCategory", notes = "Deletes an existing pizza `Category`.", authorizations = {
        @Authorization(value = "BearerAuth")    }, tags={ "pizzacategories", })
    @ApiResponses(value = { 
        @ApiResponse(code = 204, message = "Successful response.") })
    @RequestMapping(value = "/pizza/categories/{categoryId}",
        method = RequestMethod.DELETE)
    ResponseEntity<Void> deletePizzaCategory(@ApiParam(value = "A unique identifier for a `Category`.",required=true) @PathVariable("categoryId") Integer categoryId
);


    @ApiOperation(value = "List All pizza categories", nickname = "getPizzaCategories", notes = "Gets a list of all pizza `Category` entities.", response = Category.class, responseContainer = "List", authorizations = {
        @Authorization(value = "BearerAuth")    }, tags={ "pizzacategories", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Successful response - returns an array of `Category` entities.", response = Category.class, responseContainer = "List") })
    @RequestMapping(value = "/pizza/categories",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<Category>> getPizzaCategories(@ApiParam(value = "If true, the list of all entities include enabled and disabled `Category`" ) @RequestHeader(value="includeDisabled", required=false) Boolean includeDisabled
);


    @ApiOperation(value = "Get a pizza Category", nickname = "getPizzaCategory", notes = "Gets the details of a single instance of a pizza `Category`.", response = CategoryDetails.class, authorizations = {
        @Authorization(value = "BearerAuth")    }, tags={ "pizzacategories", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Successful response - returns a single `Category`.", response = CategoryDetails.class) })
    @RequestMapping(value = "/pizza/categories/{categoryId}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<CategoryDetails> getPizzaCategory(@ApiParam(value = "A unique identifier for a `Category`.",required=true) @PathVariable("categoryId") Integer categoryId
);


    @ApiOperation(value = "Update a pizza Category", nickname = "updatePizzaCategory", notes = "Updates an existing pizza `Category`.", response = CategoryDetails.class, authorizations = {
        @Authorization(value = "BearerAuth")    }, tags={ "pizzacategories", })
    @ApiResponses(value = { 
        @ApiResponse(code = 202, message = "Successful response.", response = CategoryDetails.class) })
    @RequestMapping(value = "/pizza/categories/{categoryId}",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.PUT)
    ResponseEntity<CategoryDetails> updatePizzaCategory(@ApiParam(value = "Updated `Category` information." ,required=true )  @Valid @RequestBody CategoryDetails body
,@ApiParam(value = "A unique identifier for a `Category`.",required=true) @PathVariable("categoryId") Integer categoryId
);

}
