/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.20).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.fattazzo.pizzashop.controller.api;

import com.fattazzo.pizzashop.model.api.ErrorResponse;
import com.fattazzo.pizzashop.model.api.Session;
import com.fattazzo.pizzashop.model.api.UserLogin;
import com.fattazzo.pizzashop.model.api.UserSocialLogin;
import com.fasterxml.jackson.databind.ObjectMapper;
import io.swagger.annotations.*;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.bind.annotation.CookieValue;

import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import javax.validation.constraints.*;
import java.io.IOException;
import java.util.List;
import java.util.Map;
import java.util.Optional;
@Api(value = "Session", description = "the Session API")
public interface SessionApi {

    Logger log = LoggerFactory.getLogger(SessionApi.class);

    default Optional<ObjectMapper> getObjectMapper(){
        return Optional.empty();
    }

    default Optional<HttpServletRequest> getRequest(){
        return Optional.empty();
    }

    default Optional<String> getAcceptHeader() {
        return getRequest().map(r -> r.getHeader("Accept"));
    }

    @ApiOperation(value = "Create a session", nickname = "login", notes = "Create a `Session` information", response = Session.class, authorizations = {
        @Authorization(value = "BearerAuth")    }, tags={ "session", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Login successfull", response = Session.class),
        @ApiResponse(code = 401, message = "Username or password not valid"),
        @ApiResponse(code = 403, message = "User not active", response = ErrorResponse.class) })
    @RequestMapping(value = "/public/session",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    default ResponseEntity<Session> login(@ApiParam(value = "Login user information" ,required=true )  @Valid @RequestBody UserLogin body
) {
        if(getObjectMapper().isPresent() && getAcceptHeader().isPresent()) {
            if (getAcceptHeader().get().contains("application/json")) {
                try {
                    return new ResponseEntity<>(getObjectMapper().get().readValue("{\n  \"userInfo\" : {\n    \"username\" : \"some text\",\n    \"email\" : \"some text\",\n    \"readOnly\" : true,\n    \"type\" : \"WORKER\"\n  },\n  \"enviroment\" : \"enviroment\",\n  \"locale\" : \"locale\",\n  \"accessToken\" : \"accessToken\",\n  \"refreshToken\" : \"refreshToken\"\n}", Session.class), HttpStatus.NOT_IMPLEMENTED);
                } catch (IOException e) {
                    log.error("Couldn't serialize response for content type application/json", e);
                    return new ResponseEntity<>(HttpStatus.INTERNAL_SERVER_ERROR);
                }
            }
        } else {
            log.warn("ObjectMapper or HttpServletRequest not configured in default SessionApi interface so no example is generated");
        }
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }


    @ApiOperation(value = "Create a session", nickname = "loginSocial", notes = "Create a `Session` information", response = Session.class, authorizations = {
        @Authorization(value = "BearerAuth")    }, tags={ "session", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Login successfull", response = Session.class),
        @ApiResponse(code = 401, message = "Login data not valid") })
    @RequestMapping(value = "/public/session/social",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    default ResponseEntity<Session> loginSocial(@ApiParam(value = "Login user information" ,required=true )  @Valid @RequestBody UserSocialLogin body
) {
        if(getObjectMapper().isPresent() && getAcceptHeader().isPresent()) {
            if (getAcceptHeader().get().contains("application/json")) {
                try {
                    return new ResponseEntity<>(getObjectMapper().get().readValue("{\n  \"userInfo\" : {\n    \"username\" : \"some text\",\n    \"email\" : \"some text\",\n    \"readOnly\" : true,\n    \"type\" : \"WORKER\"\n  },\n  \"enviroment\" : \"enviroment\",\n  \"locale\" : \"locale\",\n  \"accessToken\" : \"accessToken\",\n  \"refreshToken\" : \"refreshToken\"\n}", Session.class), HttpStatus.NOT_IMPLEMENTED);
                } catch (IOException e) {
                    log.error("Couldn't serialize response for content type application/json", e);
                    return new ResponseEntity<>(HttpStatus.INTERNAL_SERVER_ERROR);
                }
            }
        } else {
            log.warn("ObjectMapper or HttpServletRequest not configured in default SessionApi interface so no example is generated");
        }
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }


    @ApiOperation(value = "Create new session", nickname = "refreshToken", notes = "Create new `Session` with a valid access token", response = Session.class, authorizations = {
        @Authorization(value = "BearerAuth")    }, tags={ "session", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "New session", response = Session.class),
        @ApiResponse(code = 400, message = "Response failed", response = ErrorResponse.class) })
    @RequestMapping(value = "/public/session/refresh/{refreshToken}",
        produces = { "application/json" }, 
        method = RequestMethod.POST)
    default ResponseEntity<Session> refreshToken(@ApiParam(value = "Refresh token used for retrieve new updated session information",required=true) @PathVariable("refreshToken") String refreshToken
) {
        if(getObjectMapper().isPresent() && getAcceptHeader().isPresent()) {
            if (getAcceptHeader().get().contains("application/json")) {
                try {
                    return new ResponseEntity<>(getObjectMapper().get().readValue("{\n  \"userInfo\" : {\n    \"username\" : \"some text\",\n    \"email\" : \"some text\",\n    \"readOnly\" : true,\n    \"type\" : \"WORKER\"\n  },\n  \"enviroment\" : \"enviroment\",\n  \"locale\" : \"locale\",\n  \"accessToken\" : \"accessToken\",\n  \"refreshToken\" : \"refreshToken\"\n}", Session.class), HttpStatus.NOT_IMPLEMENTED);
                } catch (IOException e) {
                    log.error("Couldn't serialize response for content type application/json", e);
                    return new ResponseEntity<>(HttpStatus.INTERNAL_SERVER_ERROR);
                }
            }
        } else {
            log.warn("ObjectMapper or HttpServletRequest not configured in default SessionApi interface so no example is generated");
        }
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }

}
