/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.20).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.fattazzo.pizzashop.controller.api;

import com.fattazzo.pizzashop.model.api.ToppingExtra;
import com.fasterxml.jackson.databind.ObjectMapper;
import io.swagger.annotations.*;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.bind.annotation.CookieValue;

import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import javax.validation.constraints.*;
import java.io.IOException;
import java.util.List;
import java.util.Map;
import java.util.Optional;
@Api(value = "Toppingextras", description = "the Toppingextras API")
public interface ToppingextrasApi {

    Logger log = LoggerFactory.getLogger(ToppingextrasApi.class);

    default Optional<ObjectMapper> getObjectMapper(){
        return Optional.empty();
    }

    default Optional<HttpServletRequest> getRequest(){
        return Optional.empty();
    }

    default Optional<String> getAcceptHeader() {
        return getRequest().map(r -> r.getHeader("Accept"));
    }

    @ApiOperation(value = "Get a ToppingExtra", nickname = "getToppingExtra", notes = "Gets the details of a single instance of a `ToppingExtra`.", response = ToppingExtra.class, authorizations = {
        @Authorization(value = "BearerAuth")    }, tags={ "toppingextras", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Successful response - returns a single `ToppingExtra`.", response = ToppingExtra.class) })
    @RequestMapping(value = "/toppingextras/{toppingextraId}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    default ResponseEntity<ToppingExtra> getToppingExtra(@ApiParam(value = "A unique identifier for a `ToppingExtra`.",required=true) @PathVariable("toppingextraId") Integer toppingextraId
) {
        if(getObjectMapper().isPresent() && getAcceptHeader().isPresent()) {
            if (getAcceptHeader().get().contains("application/json")) {
                try {
                    return new ResponseEntity<>(getObjectMapper().get().readValue("{\n  \"extra\" : 2.3021358869347655,\n  \"id\" : 0,\n  \"variationSize\" : {\n    \"name\" : \"name\",\n    \"description\" : \"description\",\n    \"id\" : 7,\n    \"enabled\" : true,\n    \"order\" : 9\n  },\n  \"topping\" : {\n    \"name\" : \"name\",\n    \"description\" : \"description\",\n    \"id\" : 6,\n    \"enabled\" : true\n  },\n  \"dough\" : {\n    \"extra\" : 5.962133916683182,\n    \"name\" : \"name\",\n    \"description\" : \"description\",\n    \"id\" : 1,\n    \"enabled\" : true,\n    \"order\" : 5\n  },\n  \"enabled\" : true\n}", ToppingExtra.class), HttpStatus.NOT_IMPLEMENTED);
                } catch (IOException e) {
                    log.error("Couldn't serialize response for content type application/json", e);
                    return new ResponseEntity<>(HttpStatus.INTERNAL_SERVER_ERROR);
                }
            }
        } else {
            log.warn("ObjectMapper or HttpServletRequest not configured in default ToppingextrasApi interface so no example is generated");
        }
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }


    @ApiOperation(value = "List All ToppingExtras", nickname = "getToppingExtras", notes = "Gets a list of all `ToppingExtra` entities.", response = ToppingExtra.class, responseContainer = "List", authorizations = {
        @Authorization(value = "BearerAuth")    }, tags={ "toppingextras", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Successful response - returns an array of `ToppingExtra` entities.", response = ToppingExtra.class, responseContainer = "List") })
    @RequestMapping(value = "/toppingextras",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    default ResponseEntity<List<ToppingExtra>> getToppingExtras(@ApiParam(value = "Work with `sizeId` parameter" ) @RequestHeader(value="doughId", required=false) Integer doughId
,@ApiParam(value = "Work with `doughId` parameter" ) @RequestHeader(value="sizeId", required=false) Integer sizeId
) {
        if(getObjectMapper().isPresent() && getAcceptHeader().isPresent()) {
            if (getAcceptHeader().get().contains("application/json")) {
                try {
                    return new ResponseEntity<>(getObjectMapper().get().readValue("[ {\n  \"extra\" : 2.3021358869347655,\n  \"id\" : 0,\n  \"variationSize\" : {\n    \"name\" : \"name\",\n    \"description\" : \"description\",\n    \"id\" : 7,\n    \"enabled\" : true,\n    \"order\" : 9\n  },\n  \"topping\" : {\n    \"name\" : \"name\",\n    \"description\" : \"description\",\n    \"id\" : 6,\n    \"enabled\" : true\n  },\n  \"dough\" : {\n    \"extra\" : 5.962133916683182,\n    \"name\" : \"name\",\n    \"description\" : \"description\",\n    \"id\" : 1,\n    \"enabled\" : true,\n    \"order\" : 5\n  },\n  \"enabled\" : true\n}, {\n  \"extra\" : 2.3021358869347655,\n  \"id\" : 0,\n  \"variationSize\" : {\n    \"name\" : \"name\",\n    \"description\" : \"description\",\n    \"id\" : 7,\n    \"enabled\" : true,\n    \"order\" : 9\n  },\n  \"topping\" : {\n    \"name\" : \"name\",\n    \"description\" : \"description\",\n    \"id\" : 6,\n    \"enabled\" : true\n  },\n  \"dough\" : {\n    \"extra\" : 5.962133916683182,\n    \"name\" : \"name\",\n    \"description\" : \"description\",\n    \"id\" : 1,\n    \"enabled\" : true,\n    \"order\" : 5\n  },\n  \"enabled\" : true\n} ]", List.class), HttpStatus.NOT_IMPLEMENTED);
                } catch (IOException e) {
                    log.error("Couldn't serialize response for content type application/json", e);
                    return new ResponseEntity<>(HttpStatus.INTERNAL_SERVER_ERROR);
                }
            }
        } else {
            log.warn("ObjectMapper or HttpServletRequest not configured in default ToppingextrasApi interface so no example is generated");
        }
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }


    @ApiOperation(value = "Update a ToppingExtra", nickname = "updateToppingExtra", notes = "Updates an existing `ToppingExtra`.", response = ToppingExtra.class, authorizations = {
        @Authorization(value = "BearerAuth")    }, tags={ "toppingextras", })
    @ApiResponses(value = { 
        @ApiResponse(code = 202, message = "Successful response.", response = ToppingExtra.class) })
    @RequestMapping(value = "/toppingextras/{toppingextraId}",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.PUT)
    default ResponseEntity<ToppingExtra> updateToppingExtra(@ApiParam(value = "Updated `ToppingExtra` information." ,required=true )  @Valid @RequestBody ToppingExtra body
,@ApiParam(value = "A unique identifier for a `ToppingExtra`.",required=true) @PathVariable("toppingextraId") Integer toppingextraId
) {
        if(getObjectMapper().isPresent() && getAcceptHeader().isPresent()) {
            if (getAcceptHeader().get().contains("application/json")) {
                try {
                    return new ResponseEntity<>(getObjectMapper().get().readValue("{\n  \"extra\" : 2.3021358869347655,\n  \"id\" : 0,\n  \"variationSize\" : {\n    \"name\" : \"name\",\n    \"description\" : \"description\",\n    \"id\" : 7,\n    \"enabled\" : true,\n    \"order\" : 9\n  },\n  \"topping\" : {\n    \"name\" : \"name\",\n    \"description\" : \"description\",\n    \"id\" : 6,\n    \"enabled\" : true\n  },\n  \"dough\" : {\n    \"extra\" : 5.962133916683182,\n    \"name\" : \"name\",\n    \"description\" : \"description\",\n    \"id\" : 1,\n    \"enabled\" : true,\n    \"order\" : 5\n  },\n  \"enabled\" : true\n}", ToppingExtra.class), HttpStatus.NOT_IMPLEMENTED);
                } catch (IOException e) {
                    log.error("Couldn't serialize response for content type application/json", e);
                    return new ResponseEntity<>(HttpStatus.INTERNAL_SERVER_ERROR);
                }
            }
        } else {
            log.warn("ObjectMapper or HttpServletRequest not configured in default ToppingextrasApi interface so no example is generated");
        }
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }


    @ApiOperation(value = "Update All ToppingExtras", nickname = "updateToppingExtras", notes = "Updates existing `ToppingExtra`.", response = ToppingExtra.class, responseContainer = "List", authorizations = {
        @Authorization(value = "BearerAuth")    }, tags={ "toppingextras", })
    @ApiResponses(value = { 
        @ApiResponse(code = 202, message = "Successful response.", response = ToppingExtra.class, responseContainer = "List") })
    @RequestMapping(value = "/toppingextras",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.PUT)
    default ResponseEntity<List<ToppingExtra>> updateToppingExtras(@ApiParam(value = "" ,required=true )  @Valid @RequestBody List<ToppingExtra> body
) {
        if(getObjectMapper().isPresent() && getAcceptHeader().isPresent()) {
            if (getAcceptHeader().get().contains("application/json")) {
                try {
                    return new ResponseEntity<>(getObjectMapper().get().readValue("[ {\n  \"extra\" : 2.3021358869347655,\n  \"id\" : 0,\n  \"variationSize\" : {\n    \"name\" : \"name\",\n    \"description\" : \"description\",\n    \"id\" : 7,\n    \"enabled\" : true,\n    \"order\" : 9\n  },\n  \"topping\" : {\n    \"name\" : \"name\",\n    \"description\" : \"description\",\n    \"id\" : 6,\n    \"enabled\" : true\n  },\n  \"dough\" : {\n    \"extra\" : 5.962133916683182,\n    \"name\" : \"name\",\n    \"description\" : \"description\",\n    \"id\" : 1,\n    \"enabled\" : true,\n    \"order\" : 5\n  },\n  \"enabled\" : true\n}, {\n  \"extra\" : 2.3021358869347655,\n  \"id\" : 0,\n  \"variationSize\" : {\n    \"name\" : \"name\",\n    \"description\" : \"description\",\n    \"id\" : 7,\n    \"enabled\" : true,\n    \"order\" : 9\n  },\n  \"topping\" : {\n    \"name\" : \"name\",\n    \"description\" : \"description\",\n    \"id\" : 6,\n    \"enabled\" : true\n  },\n  \"dough\" : {\n    \"extra\" : 5.962133916683182,\n    \"name\" : \"name\",\n    \"description\" : \"description\",\n    \"id\" : 1,\n    \"enabled\" : true,\n    \"order\" : 5\n  },\n  \"enabled\" : true\n} ]", List.class), HttpStatus.NOT_IMPLEMENTED);
                } catch (IOException e) {
                    log.error("Couldn't serialize response for content type application/json", e);
                    return new ResponseEntity<>(HttpStatus.INTERNAL_SERVER_ERROR);
                }
            }
        } else {
            log.warn("ObjectMapper or HttpServletRequest not configured in default ToppingextrasApi interface so no example is generated");
        }
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }

}
